server:
  port: 8083
  servlet:
    context-path: /api-a

dubbo:
  consumer:
    timeout: 30000
  application:
    id: micro-dubbo-rest-a
    name: micro-dubbo-rest-a
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: micro-dubbo-provider

spring:
  application:
    name: micro-dubbo-rest-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
