server:
  port: 8080
  servlet:
    context-path: /jdbc

dubbo:
  consumer:
    timeout: 30000
  application:
    id: micro-jdbc-comsumer
    name: micro-jdbc-comsumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: micro-jdbc-provider

spring:
  application:
    name: jdbc-spring-cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
