server:
  port: 8000

spring:
  application:
    name: micro-jdbc-mq-rocketmq
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true


dubbo:
  scan:
    base-packages: com.springcloud.dubbo_provider.service
  application:
    id: micro-jdbc-mq-rocketmq
    name: micro-jdbc-mq-rocketmq
  protocol:
    id: jdbc
    name: jdbc
    port: 20881
    status: server
  registry:
    id: micro-jdbc-mq-rocketmq-registry
    address: spring-cloud://127.0.0.1

