server:
  port: 8080

spring:
  application:
    name: dubbo-spring-cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    messageTimeout: 5
    sender:
      #向http发送trace信息
      type: web
  sleuth:
    sampler:
      probability: 1.0

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: dubbo-spring-cloud-provider
  consumer:
   retries: 0
#   filter: Tracing

