server:
  port: 8000

spring:
  application:
    name: dubbo-spring-cloud-provider
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    messageTimeout: 5
    sender:
      #向http发送trace信息
      type: web
  sleuth:
    sampler:
      probability: 1.0

dubbo:
  scan:
    base-packages: com.springcloud.dubbo_provider.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  provider:
    retries: 0
    filter: Tracing

