CREATE DATABASE `ds_0` CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';
CREATE DATABASE `ds_1` CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';

CREATE TABLE `user`(
	id bigint(64) not null,
	city varchar(20) not null,
	name varchar(20) not null,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into user values(1001,'上海','尹吉欢');
insert into user values(1002,'北京','张三');

CREATE TABLE `user_0`(
	id BIGINT(64) NOT NULL,
	city VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
CREATE TABLE `user_1`(
	id BIGINT(64) NOT NULL,
	city VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
CREATE TABLE `user_2`(
	id BIGINT(64) NOT NULL,
	city VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
CREATE TABLE `user_3`(
	id BIGINT(64) NOT NULL,
	city VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
