server:
  port: 8084
  servlet:
    context-path: /api-b

dubbo:
  consumer:
    timeout: 30000
  application:
    id: micro-jdbc-rest-b
    name: micro-jdbc-rest-b
  protocol:
    name: jdbc
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: micro-jdbc-provider

spring:
  application:
    name: micro-jdbc-rest-b
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
